#!/bin/bash

function check_var
{
  if [ -z "${!1}" ]; then
    echo "WARNING: Variable $1 is undefined."
    return 1
  fi
}

[ -z "${DISTRO}" ] && export DISTRO="rpb"

if ! check_var MACHINE; then
  echo "Can't build without it."
  exit 1
fi

DEFAULT_MANIFEST_URL="https://github.com/96boards/oe-rpb-manifest"
DEFAULT_MANIFEST_BRANCH="thud"
FORCE_RINIT=""

if [ -n "${MANIFEST_URL}" -a ! "${MANIFEST_URL}" = "${DEFAULT_MANIFEST_URL}" ]; then
  FORCE_RINIT=1
fi

if [ -n "{MANIFEST_BRANCH}" -a ! "${MANIFEST_BRANCH}" = "${DEFAULT_MANIFEST_BRANCH}" ]; then
  FORCE_RINIT=1
fi

cd /oe/rpb

if [ -n "${FORCE_RINIT}" ]; then
  $HOME/bin/repo init -b "${MANIFEST_BRANCH}" -u "${MANIFEST_URL}"
fi
$HOME/bin/repo sync --force-sync

sudo chown -R oeuser /oe/rpb/build
:>>/oe/rpb/build/pre
:>>/oe/rpb/build/post
chmod 777 /oe/rpb/build/pre /oe/rpb/build/post

echo "Running with parameters: [$@]"

/bin/bash --rcfile <(cat /etc/bash.bashrc $HOME/.bashrc && echo source /oe/rpb/setup-environment build && echo /oe/rpb/build/pre && echo "$@; export ret=\$?" && echo /oe/rpb/build/post && echo "exit \$ret")
